name: EC2 Deploy

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy-to-ec2-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar comandos vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 1. Entrar a la carpeta del proyecto
            cd /home/${{ secrets.EC2_USER }}/webapp/fd-web-app
            git switch main
            
            # 2. Bajar los últimos cambios de GitHub
            git pull origin main
            
            # 3. Instalar dependencias si es necesario
            source venv/bin/activate
            pip install -r requirements.txt
            
            # 4. Reiniciar algún servicio (opcional)
            sudo systemctl restart gunicorn
